extraction:
  cpp:
    after_prepare: 
      - python report.py 64
  cobol:
    after_prepare: 
      - python report.py 64
  csharp:
    after_prepare: 
      - python report.py 64
  java:
    after_prepare: 
      - python report.py 64
  javascript:
    after_prepare: 
      - python report.py 64
  python:
    after_prepare: 
      - python report.py 64
